sprite $dynatrace [200x175/16z] {
xTS9akCW341HRKZOxlkVTvmClHMpGDIYJC8_GLufjYLupbQhrMgrMgsGY6_H6PvDgc2fAgfYcb5HnuLqROPqn7nL3ya3SV7CpAWz4pDg3axAy3yxyGm_1qR6
KehH8CxEAD5YB8QZnN26uGmSmf2H3CAdc0OfJJeD_ivGcfG1Ns9LvMUOnfa4C6ZqDCxIx0pHufXz6gNffr72cHb9FwBPfr6YUJV3f5_Yvs2eF0T3PKu6VZ9-
zWE2OncgbMF2SmErRifpG-jmlkDF7OwBxUbrDDqqWXnqWMcSyPHxUfqy1qFJSp0qJRcdrwNP6VuFEb-9eJZbdbv7uGo-HL_2U_GbFlCnb08OwKnLpIndW_Rm
hB1w6Se_nhZ_UBDyjdrcu0uR62fUniUlt_vO2cFu7II5S0Di_qx26FuFYDpJl3N4NePgb8EAeYa2LwHn3ZuPHH7j86tkaSCfVM7akgz814yQwA0oZTmKZ78W
TCPY1T6GNTYXHN4j1tKxSaSAhbAWGvx4eJsEDCp1bt8iXuGwvBgErEFWOOwq70tHSjoIrtFeSZI4qDboOE2UQ71hELAWWo_ge0iubcCvADIn71peq737Sk1o
TASToOiwm5xKiHpuYeu4dUcBEfQ3GXtfzHos7BSur25Fuk1X3bcEXcYO8rt5aQ_imDmUZdC8z6QZ7DeJ1JeIZ7D0d4F6hebHYoB3G0U6EHYSKTHJNaeEHf0Z
GPI3m1rx6Vv5qRuoPCkcIPW94IFMaeJmIDp9E3xRzosVA4r9plWU_OxloLbAPfRpRh4Ce4v6RsybS_sf_0v3-2mTZpeE2sEKB89HEw8POCqCFHvtx0w6_qEe
u6DyEZR7vy_Zg1dv27O8k4fj33jSZXpD06dPqp4VFeVfVs9mnYsCxV0v3ejc0FcduNSm13caceRFqN36EiF_ClR3xTWT3CU7a2k6qx65Ccf7pQ32S3hY6Q3_
Od1XE1sv-nRtVmYfOlWT5iYe7VMvKHXUns7n3E26gydhw3l-_0x31aQ_On_006gucfoEhU7SS8UHZEA8PPIiuMhoEMm40ooGKHmZ6A0DLvFBSRHSJVvImvxk
Skn3620DfxZBiGrX08TDepmUUGW3gEk6zJ_c344rN4qUns5Z610sZU8OpoXNK-3hYYPa5CSsEwCuyc06Hp3ER2n3ZbBOOuum8j6yxP6F1yAma4_Dll-aup37
yUVNbDdu7PkFuGz9hCp6Fmu_mwz9DQVTaHrNKmY7HNFnT30s1oCml7cibLCOlZqztfCiR_yIlHqvO3CC5QdbolIscPu9mbGL4yjlLRPJaOJWMwlLQhLQhLQ_
}
