@startuml

sprite $loadbalancer [44x38/8z] {
xTKriiD048JXdcsu_uqDYMbMLQC7cVzKdtW1M9oq043M91jOnYmIrDHgRrbZMo6-bcH4riZcdcVFuBjTCxkI23CB9V_opK3CBVxTre4LUjxR5RNlmB3P0c2Z
MJZrQIKeQsChXlnkamWR2-RMc_MXLREvv-hMsLhLw-7KqJCy9L2vz_B4JhrQuYLzJWi-RQjFYsFB65CBrzmMTlRKMWtFzu0pUyiL
}

!define TTO_LB(_alias) ENTITY(rectangle,black,LB,_alias,TTO LB)
!define TTO_LB(_alias, _label) ENTITY(rectangle,black,LB,_label, _alias,TTO LB)
!define TTO_LB(_alias, _label, _shape) ENTITY(_shape,black,LB,_label, _alias,TTO LB)
!define TTO_LB(_alias, _label, _shape, _color) ENTITY(_shape,_color,LB,_label, _alias,TTO LB)
skinparam folderBackgroundColor<<TTO LB>> White

@enduml